config/routes.rb
Rails.application.routes.draw do

  get '/signet/google/auth_callback' => 'g_cal_events#oauth2callback'

  ActiveAdmin.routes(self)

 Rails.application.routes.draw do
   devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
    }
 end

get '/admin/autocomplete_tags',
  to: 'admin/playbooks#autocomplete_tags',
  as: 'autocomplete_tags'

get '/admin/access_list',
  to: 'admin/groups#access_list',
  as: 'access_list'

post '/admin/playbooks/show_params',
  to: 'admin/playbooks#show_params',
  as: 'show_params'

  match 'process_ipn', to: 'payment_transactions#process_ipn', via: :all, as: 'process_ipn'

  resources :invitations
  resource :calendar, :only => [:show]
  resources :g_cal_events do
    collection do
      post :gmod
    end
  end
  resources :event_types
  resources :payment_transactions
  resources :payment_requests do
    get :make_payment, :key => :id
  end
  resources :events do
    resources :responses
  end
  resources :locations
  resources :people do
    resources :responses do
    put :update_responses
  end
  end
  resources :event_groups
  resources :event_users do
    resources :responses do
    put :update_responses
  end
  end
  resources :g_cals do
    collection do
      get 'select'
    end
  end

  resources :responses do
    collection do
      post :batch_update
    end
  end
  resources :uploads
  resources :playbooks
  resources :forms do
    resources :form_submissions do
      resources :form_submission_items
    end
    resources :form_fields do
      resources :form_submission_items
    end
  end
  resources :form_submissions do
    resources :form_submission_items
  end

  root :to => "landing#index"

end

app/models/g_cal_event.rb
class GCalEvent < ActiveRecord::Base
  require 'activerecord-tableless'
  require 'tzinfo'
  require 'active_support/time_with_zone'
  require 'active_support'
  require 'rubygems'

  has_no_table

  column :id, :string
  column :g_cal_event_id, :string
  column :g_iCal_uid, :string
  column :native_event_id, :integer
  column :title, :string
  column :description, :string
  column :start, :datetime
  column :end, :datetime
  column :start_tz
  column :end_tz
  column :allDay, :boolean
  column :url, :string
  column :location
  column :g_cal_id
  column :g_cal_tz
  column :is_shared, :boolean


#### TO DO ####
# Build method for stripped-down list of events that gets fed to Java for calendar
# display since the calendar display doesn't use all of the  model data.



  def self.build_events(data, g_cal_id, org_id)
    @events = []
    g_cal_tz = data.timeZone

## TO DO
## Consider reworking this to select all where g_cal_id matches and then iterate thru records matching has keys from api results
    native_event_ids = Event.google_to_native_id_hash(org_id)
    data.items.each do |item|
      item['g_cal_id'] = g_cal_id
      item['g_cal_tz'] = g_cal_tz
      item['g_cal_event_id'] = item['id']
      if native_event_ids.has_key?(item['id'])
        is_shared =  true
        item['id'] = native_event_ids[item['id']].to_s
        item['native_event_id'] = native_event_ids[item['id']]
        item['is_shared'] = true
      else
        is_shared =  false
        item['is_shared'] = false
        item['id'] = "g_cal_#{item['id']}"
        item['native_event_id'] = nil
      end
      gevent = self.google_build(item, is_shared)
      @events << gevent
    end

    nevents = Event.all_org_nativeonly_events(org_id)
    nevents.each do |item|
      nevent = self.native_build(item)
      @events << nevent
    end

    return @events
  end

  def self.google_build(item, is_shared=nil)

    if is_shared == nil
      item['g_cal_event_id'] = item['id']
      native_event = Event.find_shared_by_g_cal(item['g_cal_event_id'])

      if !(native_event.blank?)
        item['id'] = native_event
        item['is_shared'] = true
        item['native_event_id'] = native_event
      else
        item['id'] = "g_cal_#{item['id']}"
        item['is_shared'] = false
        item['native_event_id'] = nil
      end
    end

    if !!item['start']['date']
      all_day = true
      startdate = item['start']['date'].to_date.beginning_of_day
      enddate = item['end']['date'].to_date.beginning_of_day - 1
      start_tz = nil #ActiveSupport::TimeZone.find_tzinfo(item['g_cal_tz']).name
      end_tz = nil #ActiveSupport::TimeZone.find_tzinfo(item['g_cal_tz']).name
    else
      all_day = false
      startdate = item['start']['dateTime'].utc
      enddate = item['end']['dateTime'].utc
      start_tz = !!item['start']['timeZone'] ? ActiveSupport::TimeZone::MAPPING.key(item['start']['timeZone']) : nil
      end_tz = !!item['end']['timeZone'] ? ActiveSupport::TimeZone::MAPPING.key(item['end']['timeZone']) : nil
    end
    cal_tz = item['g_cal_tz']

    @event = GCalEvent.new({
      :id                 =>  item['id'],
      :title              =>  item['summary'],
      :description        =>  item['description'],
      :start              =>  startdate,
      :end                =>  enddate,
      :start_tz           =>  start_tz,
      :end_tz             =>  end_tz,
      :allDay             =>  all_day,
      :url                =>  item['htmlLink'],
      :location           =>  item['location'],
      :native_event_id    =>  item['native_event_id'],
      :g_cal_event_id     =>  item['g_cal_event_id'],
      :g_iCal_uid         =>  item['iCalUID'],
      :g_cal_id           =>  item['g_cal_id'],
      :g_cal_tz           =>  cal_tz,
      :is_shared          =>  item['is_shared']
      })
  	return @event
  end

  def self.native_build(item)

    @event = GCalEvent.new({
        :id                 =>  item.id,
        :title              =>  item.name,
        :description        =>  item.description,
        :start              =>  item.starts_at,
        :end                =>  item.ends_at,
        :start_tz           =>  nil,
        :end_tz             =>  nil,
        # :start_tz           =>  item.starts_at.zone,
        # :end_tz             =>  item.ends_at.zone,
        :allDay             =>  item.all_day,
        :url                =>  nil,
        :location           =>  item.location.name,
        :native_event_id    =>  item.id,
        :g_cal_event_id     =>  nil,
        :g_iCal_uid         =>  nil,
        :g_cal_id           =>  nil,
        :g_cal_tz           =>  nil,
        :is_shared          =>  false

  }
      )
  	return @event
  end


  # def title
  # 	@title = self.summary
  # end

  # def title=(title)
  # 	@title = self.summary
  # end

  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => self.start,
      :end => self.end,
      :allDay => self.allDay,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
      # ,
      # :is_shared => self.is_shared
      #:color => "red"
    }

  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

  # def all_day=(all_day)
  #   @all_day = !!self.start.date ? :true : :false
  # end

  # def setAll_day(item)
  #   @all_day = !!item.start.date ? :true : :false
  # end



  # def self.api_connection
  #   @api_connection = GCalEvents.build_g_cal_api
  # end

  # def api_connection=(api_connection=nil)
  #   # @api_client = GCalEvents.api_client
  #   # @user_credentials = GCalEvents.user_credentials
  #   # @calendar_api = GCalEvents.calendar_api
  #   # @g_cal_id = GCalEvents.g_cal_id
  #   if !api_connection
  #     api_connection = self.api_connection
  #   end
  #   @api_connection = api_connection
  # end

  # # def self.get_g_cal_id(org_id)
  # #   g_cal = GCal.find_by(:organization_id => org_id)
  # #   g_cal_id = g_cal.g_cal_id
  # # end
  # def self.new_g_cal_event(id)
  #   self.api_connection
  # # def self.new_g_cal_event(session,id)
  #   # self.get_api(session)
  #   # g_cal = GCal.find_by(:organization_id => session[:organization_id])
  #   # calendar = @api_client.discovered_api('calendar', 'v3')
  #   # request = @api_client.generate_request(:api_method => calendar.events.get,
  #   #                                       :parameters => {'eventId' => id, 'calendarId' => g_cal.g_cal_id}
  #   #                                       )
  #   event = @api_connection.api_client.execute(:api_method => @api_connection.calendar_api.events.get,
  #                                         :parameters => {'eventId' => id, 'calendarId' => @api_connection.g_cal_id},
  #                                         :authorization => @api_connection.credentials )
  #   @event = self.google_build(event.data, @api_connection.g_cal_id)#self.google_build(event)
  # end

#   def self.get_g_cal_events(api_connection)

#   # def self.get_g_cal_events(g_cal_id)
#     # self.api_connection
#     # self.get_api(session)
#     # calendar = @api_client.discovered_api('calendar', 'v3')
#     # request = @api_client.generate_request(:api_method => @api_connection.calendar_api.events.list,
#     #                                       :parameters => {'calendarId' => g_cal_id}
#     #                                       )
#     @event_list = api_connection.api_client.execute(:api_method => api_connection.calendar_api.events.list,
#                                           :parameters => {'calendarId' => api_connection.g_cal_id},
#                                           :authorization => api_connection.credentials )
#   end

#   def self.update_g_cal_event(id)
#     self.api_connection
#   # def self.new_g_cal_event(session,id)
#     # self.get_api(session)
#     # g_cal = GCal.find_by(:organization_id => session[:organization_id])
#     # calendar = @api_client.discovered_api('calendar', 'v3')
#     # request = @api_client.generate_request(:api_method => calendar.events.get,
#     #                                       :parameters => {'eventId' => id, 'calendarId' => g_cal.g_cal_id}
#     #                                       )
#     event = @api_connection.api_client.execute(:api_method => @api_connection.calendar_api.events.get,
#                                           :parameters => {'eventId' => id, 'calendarId' => @api_connection.g_cal_id},
#                                           :authorization => @api_connection.credentials )
#     @event = self.google_build(event.data, @api_connection.g_cal_id)#self.google_build(event)
#   end

# def self.get_api(session_data)
#       @user_credentials = Rails.application.config.google_api_client.authorization.dup
#     @api_client = Rails.application.config.google_api_client
#     if !session_data[:access_token]
#       redirect_to(@user_credentials.authorization_uri({:access_type => "offline", :approval_prompt => "force"}).to_s)
#     else
#       @user_credentials.access_token = session_data[:access_token]
#       @user_credentials.refresh_token = session_data[:refresh_token]
#       @user_credentials.code = session_data[:code]
#       @user_credentials.update_token!
#     end
# end


  #   def start=(start)
  # 	@start = !!self.start['datetime'] ? self.start.['datetime'] : self.start.date
  # end

end

app/controllers/g_cal_events_controller.rb
class GCalEventsController < ApplicationController

  require 'google/api_client'
  require 'google/api_client/client_secrets'
  require 'google/api_client/auth/file_storage'
  require 'json'
  require 'apis/google_api'
  require 'apis/g_cal_api'

  include Apis::GoogleApi

helper_method :redirect_to

  before_action :user_credentials, only: [:index, :gmod ]

  CREDENTIAL_STORE_FILE = "#{$0}-oauth2.json"



  def index
    event_list = @g_cal_api.get_g_cal_events
    # @data = JSON.pretty_generate(event_list.data)
    # @events = JSON.parse(@data)
    # @results = event_list.data.items
    @results = GCalEvent.build_events(event_list.data, g_cal.g_cal_id, session[:organization_id])
    respond_to do |format|
      format.html
      format.json { render :json => @results }
    end

# @results = @g_cal_api.user_credentials
  end

  def edit
    # g_cal_event_hash = params[:g_cal_event]
    @g_cal_event = GCalEvent.new(g_cal_event_hash_param)
    # @g_cal_event.url = g_cal_event_hash
    # respond_with @g_cal_event

  end

  def gmod

    @g_cal_event = g_cal_event_param
    update_was_successful = @g_cal_api.update_g_cal_event(@g_cal_event) == 200 ? true : false

    ## add code to redirect back to edit form if update wasn't successful

    respond_to do |format|
      if update_was_successful
        format.html { redirect_to(calendar_path, :notice => 'The Event was updated.')}
        format.json { head :no_content }
      else
        format.html { render :action => "gmod" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end

  end

  def user_credentials
    @g_cal_api = create_api
    serialize_token
  end


  #Set authorization codes and go to index
  # def oauth2callback
  #   GCalApi::oauth2callback
  # end

  def error_handling(e)
    session[:refresh_attempt_count] += 1
    if session[:refresh_attempt_count] <3
      self.refresh_token(session[:refresh_token])
    end
  end

  def g_cal_event_hash_param
    params.require(:g_cal_event).permit!
  end

  def g_cal_event_param
    params.require(:g_cal_event).permit!
  end


end

app/views/g_cal_events/_form.html.erb
<%= semantic_form_for [@g_cal_event], :url => gmod_g_cal_events_path do |form| %>
  <%= form.inputs "Event" do %>
    <%= form.label :title, "Title:" %>
    <%= form.input :title, :as => :string, :label => false %>
    <%= form.label :description, "Description:" %>
    <%= form.input :description, :as => :string, :label => false  %>
    <%= form.label :allDay, "All Day event?" %>
    <%= form.input :allDay, :as => :boolean, :checked_value => 'true', :label => false %>
        <% if form.object.allDay %>
        <%= form.label :start, "Start Date:" %>
        <%= form.input :start, :as => :date_picker, :label => false %>
        <%= form.label :end, "End Date (inclusive):" %>
        <%= form.input :end, :as => :date_picker, :label => false  %>
    <% else %>
        <%= form.label :start, "Start Date & Time:" %>
        <%= form.input :start, :as => :datetime_picker %>
        <% if form.object.start_tz != "" %>
            <%= form.label :start_tz, "Starting Timezone:" %>
            <%= form.input :start_tz, :as => :time_zone %>
        <% end %>
        <%= form.label :end, "End Date & Time:" %>
        <%= form.input :end, :as => :datetime_picker %>
        <% if form.object.end_tz != "" %>
            <%= form.label :end, "Ending Timezone:" %>
            <%= form.input :end_tz, :as => :time_zone %>
        <% end %>
    <% end %>
    <%= form.label :location, "Location:" %>
    <%= form.input :location, :as => :string, :label => false %>
    <%= form.input :id, :as => :hidden %>
    <%= form.input :g_cal_id, :as => :hidden %>
    <%= form.input :g_cal_event_id, :as => :hidden %>
    <%= form.input :native_event_id, :as => :hidden %>
    <%= form.input :url, :as => :hidden %>
    <%= form.input :is_shared, :as => :hidden %>
    <%= form.input :g_cal_id, :as => :hidden %>
  <% end %>
  <%= form.actions %>
<% end %>
<%= @g_cal_event.inspect %>

app/views/g_cal_events/_g_cal_event.html.erb
<div class = "<%= cycle('odd', 'even') %> item">
	<div class="item-header">
		<span class="item-header-title">Event: </span>
		<span class="item-header-val"><%= g_cal_event.title %></span>
	</div>

	<div class="item-attr">
		<span class="item-attr-title">All Day: </span>
		<span class="event-location item-attr-val"><%= g_cal_event.allDay %></span>
	</div>
	<% if g_cal_event.allDay == false %>
	<div datetime="<%= g_cal_event.start %>" class="item-attr">
		<span class="item-attr-title">Start: </span>
		<span class="event-location item-attr-val"><%= g_cal_event.start.to_formatted_s(:short) %></span>
	</div>
	<div datetime="<%= g_cal_event.end %>" class="item-attr">
		<span class="item-attr-title">End: </span>
		<span class="event-location item-attr-val"><%= g_cal_event.end.to_formatted_s(:short) %></span>
	</div>	
	<% else %>
	<div datetime="<%= g_cal_event.start.strftime('%m/%d/%Y')   %>" class="item-attr">
		<span class="item-attr-title">Start: </span>
		<span class="event-location item-attr-val"><%= g_cal_event.start.strftime("%m/%d/%Y")   %></span>
	</div>
	<div datetime="<%= g_cal_event.end.strftime('%m/%d/%Y')   %>" class="item-attr">
		<span class="item-attr-title">End: </span>
		<span class="event-location item-attr-val"><%= g_cal_event.end.strftime("%m/%d/%Y")   %></span>
	</div>	
	<% end %>
	<div class="item-attr">
		<span class="item-attr-title">Location: </span>
		<span class="event-location item-attr-val"><%= g_cal_event.location %></span>
	</div>
</div>

app/views/g_cal_events/edit.html.erb
<h1>Editing Google Calendar Event</h1>

<%= render 'form' %>


<%= link_to raw("&larr; Back to Calendar"), calendar_path %>

app/views/g_cal_events/gmod.html.erb
<%= @g_cal_event.inspect %>
<BR><BR>

app/views/g_cal_events/index.html.erb
<%= @results.inspect  %>
<BR>
	<BR>
		<BR>
			<%=
			# @timezones2
			%>

app/views/g_cal_events/oauth2callback.html.erb
<%= debug @user_credentials %>

app/views/g_cal_events/show.html.erb
<%=
# ActiveSupport::JSON.encode(event)
@event.inspect
 %>
<BR>